# Generated by Django 6.0.3 on 2026-03-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionlog',
            name='actual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictionlog',
            name='probability',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predictionlog',
            name='features',
            field=models.JSONField(),
        ),
    ]
