# Generated by Django 6.0.3 on 2026-03-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris_app', '0002_predictionlog_actual_predictionlog_probability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionlog',
            name='actual',
        ),
        migrations.RemoveField(
            model_name='predictionlog',
            name='probability',
        ),
        migrations.AlterField(
            model_name='predictionlog',
            name='features',
            field=models.CharField(max_length=200),
        ),
    ]
