services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: iris_db

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: on-failure
